"""Constants for Marstek BLE."""

DOMAIN = "marstek_ct"

CONF_CT_MAC = "ct_mac"
CONF_CT_POLL_INTERVAL = "ct_poll_interval"
CONF_VENUS_POLL_INTERVAL = "venus_poll_interval"
CONF_VENUS_DEVICES = "venus_devices"

DEFAULT_CT_POLL_INTERVAL = 5
MIN_CT_POLL_INTERVAL = 5
MAX_CT_POLL_INTERVAL = 300

DEFAULT_VENUS_POLL_INTERVAL = 150
MIN_VENUS_POLL_INTERVAL = 30
MAX_VENUS_POLL_INTERVAL = 3600

CT_MODEL = "CT002"
VENUS_MODEL = "Venus E V3"

HARD_FAILURE_AFTER = 4
