name: Validate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
